# Generated by Django 5.1.4 on 2025-01-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0004_alter_course_description_alter_course_name'),
        ('lms_core', '0011_alter_comment_updated_at_alter_profile_phone_and_more'),
    ]

    operations = [
    ]
